
# compile options (see README.md for descriptions)
# 0 = disable
# 1 = enable

# ENABLE_FMRADIO - Size : 4220 Byte
# ---- STOCK QUANSHENG FERATURES ----
ENABLE_UART                   ?= 1
ENABLE_AIRCOPY                ?= 0
ENABLE_FMRADIO                ?= 0
ENABLE_NOAA                   ?= 0
ENABLE_VOICE                  ?= 0
ENABLE_VOX                    ?= 1
ENABLE_ALARM                  ?= 0
ENABLE_TX1750                 ?= 0
ENABLE_PWRON_PASSWORD         ?= 0
ENABLE_DTMF_CALLING           ?= 0	#Default Disabled by KD8CEC
ENABLE_FLASHLIGHT             ?= 1

# ---- STOCK QUANSHENG FERATURES for Reduce Usage Flash memroy ----
ENABLE_SCRAMBLER              ?= 0
ENABLE_BCL                    ?= 0
ENABLE_10TIME_TRY_UNALL_LOCK  ?= 0
ENABLE_TX_STOP_BY_CHIPRANGE   ?= 0
ENABLE_HAMBAND_TX_CONTROL     ?= 1

#D ST, D PREL, D LIVE, 
ENABLE_DTMF_RECEIVE           ?= 0
ENABLE_UPDOWN_CODE            ?= 0

#--- ADDED
ENABLE_HAMBAND_TX_CONTROL     ?= 1
ENABLE_CEC_SSTV				  ?= 1
ENABLE_CEC_CWTX				  ?= 1
#---- PADDLE WPM > 20 USING TIMER WITHOUT K-PAD, K-STRAIGHT, BUT INCLUDE IAMBIC B, not expert mode : 62204, 62480 (+ 276), so if not enough memory remove vox (61816)
ENABLE_CEC_CWTX_EXPERT	  	  ?= 1
ENABLE_CEC_CAT                ?= 1
ENABLE_CEC_RTTY               ?= 1
ENABLE_CEC_APRS               ?= 1
ENABLE_CEC_FT4_FT8            ?= 1
ENABLE_CEC_CW_DECODE          ?= 1
# ---- END OF KD8CEC WORK ------------------------------------------

#plan reduce program memory, fm radio mod, enable_small_bold disable (61148 -> 60536), f_cal_menu (60536 -> 60380), AUDIO_BAR (60380 -> 60076) : total 1KByte
#small bold using just RX, TX and Channel Name, RX, TX
# ---- CUSTOM MODS ----
ENABLE_BIG_FREQ               ?= 1
ENABLE_SMALL_BOLD             ?= 0
ENABLE_CUSTOM_MENU_LAYOUT     ?= 1
ENABLE_KEEP_MEM_NAME          ?= 1
ENABLE_WIDE_RX                ?= 1
ENABLE_TX_WHEN_AM             ?= 1
ENABLE_F_CAL_MENU             ?= 1
ENABLE_CTCSS_TAIL_PHASE_SHIFT ?= 0
ENABLE_BOOT_BEEPS             ?= 0
ENABLE_SHOW_CHARGE_LEVEL      ?= 0
ENABLE_REVERSE_BAT_SYMBOL     ?= 0
ENABLE_NO_CODE_SCAN_TIMEOUT   ?= 1
ENABLE_AM_FIX                 ?= 1
ENABLE_SQUELCH_MORE_SENSITIVE ?= 1
ENABLE_FASTER_CHANNEL_SCAN    ?= 1
ENABLE_RSSI_BAR               ?= 1
ENABLE_AUDIO_BAR              ?= 1
ENABLE_COPY_CHAN_TO_VFO       ?= 1
#DEFAULT 1 VERSION 0.1P CHANGED 0
ENABLE_SPECTRUM               ?= 0
ENABLE_REDUCE_LOW_MID_TX_POWER?= 0
ENABLE_BYP_RAW_DEMODULATORS   ?= 0
ENABLE_BLMIN_TMP_OFF          ?= 0
ENABLE_SCAN_RANGES            ?= 1
ENABLE_SSTV_APRS_SIDETOME     ?= 1

# ---- VERSION 0.3A  (increase 100 byte)
ENABLE_CEC_INTERFACE_CABLE    ?= 0
ENABLE_VOLT_HIGH_CHECK        ?= 1


# ---- DEBUGGING ----
ENABLE_AM_FIX_SHOW_DATA       ?= 0
ENABLE_AGC_SHOW_DATA          ?= 0
ENABLE_UART_RW_BK_REGS        ?= 0

# ---- COMPILER/LINKER OPTIONS ----
ENABLE_CLANG                  ?= 0
ENABLE_SWD                    ?= 0
ENABLE_OVERLAY                ?= 0
ENABLE_LTO                    ?= 1


#---- FIXED OPTION FOR REDUCE PROGRAM MEMORY
# Values that are always enabled by default without the need for a menu
# FIXED VALUE IS 2 (LIVE +)
ENABLE_LIVE_SEEKMODE_MENU     ?= 0
# FIXED VALUE IS 2K+ (Highest performance)
ENABLE_SSB_BW_MENU            ?= 0
# FIXED VALUE IS ON (Not Apply)
ENABLE_AMFIXED_MENU           ?= 1
# MENU_BAT_TXT  60828
ENABLE_BAT_TXT_MENU           ?= 0

#############################################################

TARGET = firmware

ifeq ($(ENABLE_CLANG),1)
	# GCC's linker, ld, doesn't understand LLVM's generated bytecode
	ENABLE_LTO := 0
endif

ifeq ($(ENABLE_LTO),1)
	# can't have LTO and OVERLAY enabled at same time
	ENABLE_OVERLAY := 0
endif

BSP_DEFINITIONS := $(wildcard hardware/*/*.def)
BSP_HEADERS     := $(patsubst hardware/%,bsp/%,$(BSP_DEFINITIONS))
BSP_HEADERS     := $(patsubst %.def,%.h,$(BSP_HEADERS))

OBJS =
# Startup files
OBJS += start.o
OBJS += init.o
ifeq ($(ENABLE_OVERLAY),1)
	OBJS += sram-overlay.o
endif
OBJS += external/printf/printf.o

#################### ADDED BY KD8CEC  ###################
# IF YOU USE THIS FUNCTION, COPY BELOW TO OTHER FIRMWARE#
#########################################################
OBJS += ceccommon.o
OBJS += cecsstv1.o
OBJS += cecaprs.o
OBJS += ceccat.o
OBJS += cecmorse.o
OBJS += cecrtty.o
OBJS += cecgps.o
OBJS += minmea.o
OBJS += cectimer.o
OBJS += cecspectrum.o
OBJS += cecfmradio.o
OBJS += cecdigital.o
OBJS += cecswuart.o
OBJS += cecwsprsend.o
################### END OF ADDED BY KD8CEC ##############

# Drivers
OBJS += driver/adc.o
ifeq ($(ENABLE_UART),1)
	OBJS += driver/aes.o
endif
OBJS += driver/backlight.o
ifeq ($(ENABLE_FMRADIO),1)
	OBJS += driver/bk1080.o
endif
OBJS += driver/bk4819.o
ifeq ($(filter $(ENABLE_AIRCOPY) $(ENABLE_UART),1),1)
	OBJS += driver/crc.o
endif
OBJS += driver/eeprom.o
ifeq ($(ENABLE_OVERLAY),1)
	OBJS += driver/flash.o
endif
OBJS += driver/gpio.o
OBJS += driver/i2c.o
OBJS += driver/keyboard.o
OBJS += driver/spi.o
OBJS += driver/st7565.o
OBJS += driver/system.o
OBJS += driver/systick.o
ifeq ($(ENABLE_UART),1)
	OBJS += driver/uart.o
endif

# Main
OBJS += app/action.o
ifeq ($(ENABLE_AIRCOPY),1)
	OBJS += app/aircopy.o
endif
OBJS += app/app.o
OBJS += app/chFrScanner.o
OBJS += app/common.o
OBJS += app/dtmf.o
ifeq ($(ENABLE_FLASHLIGHT),1)
	OBJS += app/flashlight.o
endif
ifeq ($(ENABLE_FMRADIO),1)
	OBJS += app/fm.o
endif
OBJS += app/generic.o
OBJS += app/main.o
OBJS += app/menu.o
ifeq ($(ENABLE_SPECTRUM), 1)
OBJS += app/spectrum.o
endif
OBJS += app/scanner.o
ifeq ($(ENABLE_UART),1)
	OBJS += app/uart.o
endif
ifeq ($(ENABLE_AM_FIX), 1)
	OBJS += am_fix.o
endif
OBJS += audio.o
OBJS += bitmaps.o
OBJS += board.o
OBJS += dcs.o
OBJS += font.o
OBJS += frequencies.o
OBJS += functions.o
OBJS += helper/battery.o
OBJS += helper/boot.o
OBJS += misc.o
OBJS += radio.o
OBJS += scheduler.o
OBJS += settings.o
ifeq ($(ENABLE_AIRCOPY),1)
	OBJS += ui/aircopy.o
endif
OBJS += ui/battery.o
ifeq ($(ENABLE_FMRADIO),1)
	OBJS += ui/fmradio.o
endif
OBJS += ui/helper.o
OBJS += ui/inputbox.o
ifeq ($(ENABLE_PWRON_PASSWORD),1)
	OBJS += ui/lock.o
endif
OBJS += ui/main.o
OBJS += ui/menu.o
OBJS += ui/scanner.o
OBJS += ui/status.o
OBJS += ui/ui.o
OBJS += ui/welcome.o
OBJS += version.o
OBJS += main.o

ifeq ($(OS), Windows_NT) # windows
    TOP := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
    RM = del /Q
    FixPath = $(subst /,\,$1)
    WHERE = where
    NULL_OUTPUT = nul
else # unix
    TOP := $(shell pwd)
    RM = rm -f
    FixPath = $1
    WHERE = which
    NULL_OUTPUT = /dev/null
endif

AS = arm-none-eabi-gcc
LD = arm-none-eabi-gcc

ifeq ($(ENABLE_CLANG),0)
	CC = arm-none-eabi-gcc
# Use GCC's linker to avoid undefined symbol errors
#	LD += arm-none-eabi-gcc
else
#	May need to adjust this to match your system
	CC = clang --sysroot=/usr/arm-none-eabi --target=arm-none-eabi
#	Bloats binaries to 512MB
#	LD = ld.lld
endif

OBJCOPY = arm-none-eabi-objcopy
SIZE = arm-none-eabi-size

# CHANGE AUTHOR
#It is only used to specify the source code and is no longer used (it is not compiled).
AUTHOR_STRING ?= KD8CEC_FROM_SOURCE_CODE_EGZUMER
# the user might not have/want git installed
# can set own version string here (max 7 chars)

# CHANGE VERSION TYPE
VERSION_STRING ?= CEC_0.3V


ASFLAGS = -c -mcpu=cortex-m0
ifeq ($(ENABLE_OVERLAY),1)
	ASFLAGS += -DENABLE_OVERLAY
endif

CFLAGS =
ifeq ($(ENABLE_CLANG),0)
	CFLAGS += -Os -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=c11 -MMD
	#CFLAGS += -Os -Wall -Werror -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=c2x -MMD
	#CFLAGS += -Os -Wall -Werror -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=c11 -MMD
	#CFLAGS += -Os -Wall -Werror -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=c99 -MMD
	#CFLAGS += -Os -Wall -Werror -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=gnu99 -MMD
	#CFLAGS += -Os -Wall -Werror -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=gnu11 -MMD
else
	# Oz needed to make it fit on flash
	CFLAGS += -Oz -Wall -Werror -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=c2x -MMD
endif

ifeq ($(ENABLE_LTO),1)
	CFLAGS += -flto=auto
else
	# We get most of the space savings if LTO creates problems
	CFLAGS += -ffunction-sections -fdata-sections
endif

# May cause unhelpful build failures
#CFLAGS += -Wpadded

# catch any and all warnings
CFLAGS += -Wextra
#CFLAGS += -Wpedantic

CFLAGS += -DPRINTF_INCLUDE_CONFIG_H
CFLAGS += -DAUTHOR_STRING=\"$(AUTHOR_STRING)\" -DVERSION_STRING=\"$(VERSION_STRING)\"

ifeq ($(ENABLE_CEC_INTERFACE_CABLE),1)
CFLAGS += -DENABLE_CEC_INTERFACE_CABLE
endif

ifeq ($(ENABLE_VOLT_HIGH_CHECK),1)
CFLAGS += -DENABLE_VOLT_HIGH_CHECK
endif


ifeq ($(ENABLE_LIVE_SEEKMODE_MENU),1)
CFLAGS += -DENABLE_LIVE_SEEKMODE_MENU
endif
ifeq ($(ENABLE_SSB_BW_MENU),1)
CFLAGS += -DENABLE_SSB_BW_MENU
endif
ifeq ($(ENABLE_AMFIXED_MENU),1)
CFLAGS += -DENABLE_AMFIXED_MENU
endif

ifeq ($(ENABLE_BAT_TXT_MENU),1)
CFLAGS += -DENABLE_BAT_TXT_MENU
endif

ifeq ($(ENABLE_SSTV_APRS_SIDETOME),1)
CFLAGS += -DENABLE_SSTV_APRS_SIDETOME
endif

ifeq ($(ENABLE_SPECTRUM),1)
CFLAGS += -DENABLE_SPECTRUM
endif
ifeq ($(ENABLE_SWD),1)
	CFLAGS += -DENABLE_SWD
endif
ifeq ($(ENABLE_OVERLAY),1)
	CFLAGS += -DENABLE_OVERLAY
endif
ifeq ($(ENABLE_AIRCOPY),1)
	CFLAGS += -DENABLE_AIRCOPY
endif
ifeq ($(ENABLE_FMRADIO),1)
	CFLAGS += -DENABLE_FMRADIO
endif
ifeq ($(ENABLE_UART),1)
	CFLAGS += -DENABLE_UART
endif
ifeq ($(ENABLE_BIG_FREQ),1)
	CFLAGS  += -DENABLE_BIG_FREQ
endif
ifeq ($(ENABLE_SMALL_BOLD),1)
	CFLAGS  += -DENABLE_SMALL_BOLD
endif
ifeq ($(ENABLE_NOAA),1)
	CFLAGS  += -DENABLE_NOAA
endif
ifeq ($(ENABLE_VOICE),1)
	CFLAGS  += -DENABLE_VOICE
endif
ifeq ($(ENABLE_VOX),1)
	CFLAGS  += -DENABLE_VOX
endif
ifeq ($(ENABLE_ALARM),1)
	CFLAGS  += -DENABLE_ALARM
endif
ifeq ($(ENABLE_TX1750),1)
	CFLAGS  += -DENABLE_TX1750
endif
ifeq ($(ENABLE_PWRON_PASSWORD),1)
	CFLAGS  += -DENABLE_PWRON_PASSWORD
endif
ifeq ($(ENABLE_KEEP_MEM_NAME),1)
	CFLAGS  += -DENABLE_KEEP_MEM_NAME
endif
ifeq ($(ENABLE_WIDE_RX),1)
	CFLAGS  += -DENABLE_WIDE_RX
endif
ifeq ($(ENABLE_TX_WHEN_AM),1)
	CFLAGS  += -DENABLE_TX_WHEN_AM
endif
ifeq ($(ENABLE_F_CAL_MENU),1)
	CFLAGS  += -DENABLE_F_CAL_MENU
endif
ifeq ($(ENABLE_CTCSS_TAIL_PHASE_SHIFT),1)
	CFLAGS  += -DENABLE_CTCSS_TAIL_PHASE_SHIFT
endif
ifeq ($(ENABLE_BOOT_BEEPS),1)
	CFLAGS  += -DENABLE_BOOT_BEEPS
endif
ifeq ($(ENABLE_SHOW_CHARGE_LEVEL),1)
	CFLAGS  += -DENABLE_SHOW_CHARGE_LEVEL
endif
ifeq ($(ENABLE_REVERSE_BAT_SYMBOL),1)
	CFLAGS  += -DENABLE_REVERSE_BAT_SYMBOL
endif
ifeq ($(ENABLE_NO_CODE_SCAN_TIMEOUT),1)
	CFLAGS  += -DENABLE_CODE_SCAN_TIMEOUT
endif
ifeq ($(ENABLE_AM_FIX),1)
	CFLAGS  += -DENABLE_AM_FIX
endif
ifeq ($(ENABLE_AM_FIX_SHOW_DATA),1)
	CFLAGS  += -DENABLE_AM_FIX_SHOW_DATA
endif
ifeq ($(ENABLE_SQUELCH_MORE_SENSITIVE),1)
	CFLAGS  += -DENABLE_SQUELCH_MORE_SENSITIVE
endif
ifeq ($(ENABLE_FASTER_CHANNEL_SCAN),1)
	CFLAGS  += -DENABLE_FASTER_CHANNEL_SCAN
endif
ifeq ($(ENABLE_BACKLIGHT_ON_RX),1)
	CFLAGS  += -DENABLE_BACKLIGHT_ON_RX
endif
ifeq ($(ENABLE_RSSI_BAR),1)
	CFLAGS  += -DENABLE_RSSI_BAR
endif
ifeq ($(ENABLE_AUDIO_BAR),1)
	CFLAGS  += -DENABLE_AUDIO_BAR
endif
ifeq ($(ENABLE_COPY_CHAN_TO_VFO),1)
	CFLAGS  += -DENABLE_COPY_CHAN_TO_VFO
endif
ifeq ($(ENABLE_SINGLE_VFO_CHAN),1)
	CFLAGS  += -DENABLE_SINGLE_VFO_CHAN
endif
ifeq ($(ENABLE_BAND_SCOPE),1)
	CFLAGS += -DENABLE_BAND_SCOPE
endif
ifeq ($(ENABLE_REDUCE_LOW_MID_TX_POWER),1)
	CFLAGS  += -DENABLE_REDUCE_LOW_MID_TX_POWER
endif
ifeq ($(ENABLE_BYP_RAW_DEMODULATORS),1)
	CFLAGS  += -DENABLE_BYP_RAW_DEMODULATORS
endif
ifeq ($(ENABLE_BLMIN_TMP_OFF),1)
	CFLAGS  += -DENABLE_BLMIN_TMP_OFF
endif
ifeq ($(ENABLE_SCAN_RANGES),1)
	CFLAGS  += -DENABLE_SCAN_RANGES
endif
ifeq ($(ENABLE_DTMF_CALLING),1)
	CFLAGS  += -DENABLE_DTMF_CALLING
endif
ifeq ($(ENABLE_AGC_SHOW_DATA),1)
	CFLAGS  += -DENABLE_AGC_SHOW_DATA
endif
ifeq ($(ENABLE_FLASHLIGHT),1)
	CFLAGS  += -DENABLE_FLASHLIGHT
endif
ifeq ($(ENABLE_UART_RW_BK_REGS),1)
	CFLAGS  += -DENABLE_UART_RW_BK_REGS
endif
ifeq ($(ENABLE_CUSTOM_MENU_LAYOUT),1)
	CFLAGS  += -DENABLE_CUSTOM_MENU_LAYOUT
endif

# KD8CEC WORK
# ---- STOCK QUANSHENG FERATURES for Reduce Usage Flash memroy ----
ifeq ($(ENABLE_BCL),1)
	CFLAGS  += -DENABLE_BCL
endif
ifeq ($(ENABLE_SCRAMBLER),1)
	CFLAGS  += -DENABLE_SCRAMBLER
endif
ifeq ($(ENABLE_10TIME_TRY_UNALL_LOCK),1)
	CFLAGS  += -DENABLE_10TIME_TRY_UNALL_LOCK
endif
ifeq ($(ENABLE_TX_STOP_BY_CHIPRANGE),1)
	CFLAGS  += -DENABLE_TX_STOP_BY_CHIPRANGE
endif
ifeq ($(ENABLE_HAMBAND_TX_CONTROL),1)
	CFLAGS  += -DENABLE_HAMBAND_TX_CONTROL
endif

ifeq ($(ENABLE_DTMF_RECEIVE),1)
CFLAGS += -DENABLE_DTMF_RECEIVE
endif
ifeq ($(ENABLE_UPDOWN_CODE),1)
CFLAGS += -DENABLE_UPDOWN_CODE
endif
# ---- END OF option for stock firmware features

ifeq ($(ENABLE_CEC_SSTV),1)
CFLAGS += -DENABLE_CEC_SSTV
endif

ifeq ($(ENABLE_CEC_CWTX),1)
CFLAGS += -DENABLE_CEC_CWTX
endif

ifeq ($(ENABLE_CEC_CWTX_EXPERT),1)
CFLAGS += -DENABLE_CEC_CWTX_EXPERT
endif

ifeq ($(ENABLE_CEC_CAT),1)
CFLAGS += -DENABLE_CEC_CAT
endif
ifeq ($(ENABLE_CEC_RTTY),1)
CFLAGS += -DENABLE_CEC_RTTY
endif
ifeq ($(ENABLE_CEC_APRS),1)
CFLAGS += -DENABLE_CEC_APRS
endif
ifeq ($(ENABLE_CEC_FT4_FT8),1)
CFLAGS += -DENABLE_CEC_FT4_FT8
endif
ifeq ($(ENABLE_CEC_CW_DECOD),1)
CFLAGS += -DENABLE_CEC_CW_DECOD
endif

# END OF KD8CEC WORK


LDFLAGS =
LDFLAGS += -z noexecstack -mcpu=cortex-m0 -nostartfiles -Wl,-T,firmware.ld -Wl,--gc-sections

# Use newlib-nano instead of newlib
LDFLAGS += --specs=nano.specs

ifeq ($(DEBUG),1)
	ASFLAGS += -g
	CFLAGS  += -g
	LDFLAGS += -g
endif

INC =
INC += -I $(TOP)
INC += -I $(TOP)/external/CMSIS_5/CMSIS/Core/Include/
INC += -I $(TOP)/external/CMSIS_5/Device/ARM/ARMCM0/Include

LIBS =

DEPS = $(OBJS:.o=.d)



ifneq (, $(shell $(WHERE) python))
    MY_PYTHON := python
else ifneq (, $(shell $(WHERE) python3))
    MY_PYTHON := python3
endif

ifdef MY_PYTHON
    HAS_CRCMOD := $(shell $(MY_PYTHON) -c "import crcmod" 2>&1)
endif

all: $(TARGET)
	$(OBJCOPY) -O binary $< $<.bin

ifndef MY_PYTHON
	$(info )
	$(info !!!!!!!! PYTHON NOT FOUND, *.PACKED.BIN WON'T BE BUILT)
	$(info )
else ifneq (,$(HAS_CRCMOD))
	$(info )
	$(info !!!!!!!! CRCMOD NOT INSTALLED, *.PACKED.BIN WON'T BE BUILT)
	$(info !!!!!!!! run: pip install crcmod)
	$(info )
else
	-$(MY_PYTHON) fw-pack.py $<.bin $(AUTHOR_STRING) $(VERSION_STRING) $<.packed.bin
endif

	$(SIZE) $<

debug:
	/opt/openocd/bin/openocd -c "bindto 0.0.0.0" -f interface/jlink.cfg -f dp32g030.cfg

flash:
	/opt/openocd/bin/openocd -c "bindto 0.0.0.0" -f interface/jlink.cfg -f dp32g030.cfg -c "write_image firmware.bin 0; shutdown;"

version.o: .FORCE

$(TARGET): $(OBJS)
	$(LD) $(LDFLAGS) $^ -o $@ $(LIBS)

bsp/dp32g030/%.h: hardware/dp32g030/%.def

%.o: %.c | $(BSP_HEADERS)
	$(CC) $(CFLAGS) $(INC) -c $< -o $@

%.o: %.S
	$(AS) $(ASFLAGS) $< -o $@

.FORCE:

-include $(DEPS)

clean:
	$(RM) $(call FixPath, $(TARGET).bin $(TARGET).packed.bin $(TARGET) $(OBJS) $(DEPS))

doxygen:
	doxygen
